FROM awegierska/ros2_humble:lab_mobile_robots_base
LABEL maintainer="wegierska.agnieszka@gmail.com"

ENV USER=ubuntu

COPY ./jupyter_notebooks /home/ubuntu/turtlebot3_ws/src/jupyter_notebooks
COPY ./files_to_copy/bashrc /home/ubuntu/.bashrc
