version: "3"
services:
    lab_mobilne:
        image: awegierska/lab_ros_noetic:lab_mobilne
        environment:
            TZ: "Europe/Warsaw"
        volumes:
            - ./Desktop:/home/ubuntu/Desktop/
        ports: 
            - 6080:80
            - 8888:8888
        shm_size: '2gb'
        container_name: lab_mobilne
    
    
      
