FROM awegierska/ros2_humble:lab_mobile_ROS2_base
LABEL maintainer="wegierska.agnieszka@gmail.com"

ENV USER=ubuntu

#iCreate
# from https://github.com/iRobotEducation/create3-docker/blob/main/create3-humble/Dockerfile
ENV TZ=Europe/Warsaw
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#######
# Install Gazebo ignition fortress
#######
RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*
RUN sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
RUN wget http://packages.osrfoundation.org/gazebo.key -O - | apt-key add -
RUN apt-get update && apt-get install -y \
        ignition-fortress \
        ros-humble-ros-ign-bridge \
        ros-humble-ros-ign-gazebo \
        ros-humble-ros-ign-interfaces \
        ros-humble-foxglove-bridge \
        ros-humble-rqt \
        iputils-ping \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install -U \
        "numpy<2.0" && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /home/ubuntu/create3_ws/src && cd /home/ubuntu/create3_ws/src && \
    git clone -b humble https://github.com/iRobotEducation/create3_sim.git && \
    git clone -b humble https://github.com/iRobotEducation/create3_examples.git && \
    git clone -b humble https://github.com/iRobotEducation/irobot_create_msgs.git && \
    git clone -b ros2 https://github.com/aws-robotics/aws-robomaker-small-house-world.git

RUN apt-get update && cd /home/ubuntu/create3_ws && \
    rosdep install --from-path src -yi --rosdistro humble && rm -rf /var/lib/apt/lists/*
RUN cd /home/ubuntu/create3_ws && . /opt/ros/humble/setup.sh && colcon build --symlink-install

RUN mkdir -p /home/ubuntu/create3_ws/src
COPY ./files_to_copy/bashrc /home/ubuntu/.bashrc

RUN apt-get update && apt-get install -y \
        sqlite3 \
    && rm -rf /var/lib/apt/lists/*

#RUN ls

COPY ./files_to_copy/entrypoint.sh /
RUN dos2unix /entrypoint.sh && chmod +x /entrypoint.sh
ENTRYPOINT [ "/bin/bash", "-c", "/entrypoint.sh" ]

# konfiguracja Open-RMF
RUN apt-get update && apt-get install -y \
        ros-dev-tools \
    && rm -rf /var/lib/apt/lists/*
RUN colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml && colcon mixin update default

# TODO dodanie instalki i pobrania repo

