services:
    ros2:
        image: awegierska/ros2_humble:lab_mobile_ROS2
        container_name: lab_mobilne_ROS2
        volumes:
            - ./common_dir:/home/ubuntu/Desktop/common_dir
            - ./gazebo:/home/ubuntu/.gazebo
        ports:
            - 6080:80
            - 8888:8888
        shm_size: '2g'
        privileged: true
